# Generated by Django 4.2 on 2026-08-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='alergico',
            field=models.BooleanField(default=False, help_text='Marcar si la mascota no puede recibir vacunas por alergia.', verbose_name='Alérgico a las vacunas'),
        ),
    ]
