# Generated by Django 4.2.30 on 2026-09-28 16:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mascotas', '0002_mascota_alergico'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, help_text='Raza de la mascota (ej: Labrador, Siames, Angora...)', max_length=100, null=True, verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='La edad no puede ser negativa.'), django.core.validators.MaxValueValidator(40, message='La edad no puede ser mayor a 40 años.')]),
        ),
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('whatsapp', models.CharField(blank=True, help_text='Número de WhatsApp para contacto (opcional).', max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono fijo o celular alternativo (opcional).', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, help_text='Dirección de domicilio del dueño (opcional).', max_length=200, null=True)),
                ('email', models.EmailField(blank=True, help_text='Correo para notificaciones (opcional).', max_length=150, null=True, verbose_name='Correo electrónico')),
                ('user', models.ForeignKey(help_text='Usuario registrado del sistema asociado a este dueño.', on_delete=django.db.models.deletion.CASCADE, related_name='duenos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dueños',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='mascota',
            name='dueno',
            field=models.ForeignKey(blank=True, help_text='Dueño registrado del sistema. Opcional al crear la mascota.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='mascotas.dueño', verbose_name='Dueño'),
        ),
    ]
