# Generated by Django 4.2.30 on 2026-09-27 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_mascota_alergico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='La edad no puede ser negativa.'), django.core.validators.MaxValueValidator(40, message='La edad no puede ser mayor a 40 años.')]),
        ),
    ]
