# Generated by Django 4.2.30 on 2026-09-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_mascota_raza_alter_mascota_edad_dueño_mascota_dueno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascota',
            options={},
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('multivitaminica', 'Multivitamínica'), ('antirrabica', 'Antirrábica'), ('triple_virus', 'Triple virus'), ('covid_canino', 'COVID Canino'), ('rabia', 'Rabia'), ('otra', 'Otra')], max_length=30, verbose_name='Tipo de vacuna')),
                ('fecha_aplicacion', models.DateField(verbose_name='Fecha de aplicación')),
                ('proxima_dosis', models.DateField(blank=True, help_text='Fecha cuando se debe aplicar la siguiente dosis.', null=True, verbose_name='Próxima dosis')),
                ('lote', models.CharField(blank=True, help_text='Número de lote del fabricante.', max_length=50, null=True, verbose_name='Nº de lote')),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='mascotas.mascota', verbose_name='Mascota')),
            ],
            options={
                'verbose_name_plural': 'Vacunas',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del registro')),
                ('diagnostico', models.CharField(blank=True, max_length=300, null=True, verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, null=True, verbose_name='Tratamiento indicado')),
                ('veterinario', models.CharField(max_length=100, verbose_name='Veterinario')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='mascotas.mascota', verbose_name='Mascota')),
            ],
            options={
                'verbose_name_plural': 'Históricos médicos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veterinario', models.CharField(max_length=100, verbose_name='Veterinario a cargo')),
                ('fecha', models.DateField(verbose_name='Fecha de la cita')),
                ('hora', models.TimeField(verbose_name='Hora de la cita')),
                ('motivo', models.CharField(blank=True, help_text='Ej: chequeo anual, vacunación, lesión...', max_length=200, null=True, verbose_name='Motivo de la consulta')),
                ('observaciones', models.TextField(blank=True, help_text='Notas de la cita (llenado por el veterinario).', null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Estado')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='mascotas.mascota', verbose_name='Mascota')),
            ],
            options={
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
