# Generated by Django 4.2.30 on 2026-09-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_alter_mascota_edad'),
        ('mascotas', '0004_alter_mascota_options_vacuna_historialmedico_cita'),
    ]

    operations = [
    ]
