# Generated by Django 4.2.30 on 2026-09-30 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_merge_20260929_0231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha', 'hora'], 'permissions': [('view_own_citas', 'Puede ver solo sus propias citas')], 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='dueño',
            options={'ordering': ['nombre'], 'permissions': [('view_own_mascotas', 'Puede ver solo sus propias mascotas')], 'verbose_name_plural': 'Dueños'},
        ),
        migrations.AlterModelOptions(
            name='historialmedico',
            options={'ordering': ['-fecha'], 'permissions': [('view_own_historial', 'Puede ver solo su propio historial')], 'verbose_name_plural': 'Históricos médicos'},
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ['nombre'], 'permissions': [('view_historial_medico', 'Puede ver el historial médico completo'), ('manage_vacunas', 'Puede gestionar vacunas de cualquier mascota'), ('view_own_mascotas', 'Puede ver solo sus propias mascotas')], 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AlterModelOptions(
            name='vacuna',
            options={'ordering': ['-fecha_aplicacion'], 'permissions': [('view_own_vacunas', 'Puede ver solo sus propias vacunas')], 'verbose_name_plural': 'Vacunas'},
        ),
    ]
