# Generated by Django 4.2.30 on 2026-09-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_permisos_personalizados'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuna',
            name='alerta_enviada_el',
            field=models.DateField(blank=True, help_text='Fecha en que se envió el recordatorio por correo de la próxima dosis.', null=True, verbose_name='Alerta enviada el'),
        ),
    ]
