# Generated by Django 4.2.30 on 2026-09-30 00:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0007_vacuna_alerta_enviada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de emisión')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de débito'), ('credito', 'Tarjeta de crédito'), ('transferencia', 'Transferencia')], max_length=20, verbose_name='Método de pago')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='mascotas.cita', verbose_name='Cita asociada')),
                ('dueno', models.ForeignKey(help_text='No se puede borrar un dueño que tiene facturas.', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='mascotas.dueño', verbose_name='Dueño')),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='mascotas.mascota', verbose_name='Mascota atendida')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha', '-id'],
                'permissions': [('view_own_facturas', 'Puede ver solo sus propias facturas')],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='La cantidad mínima es 1.'), django.core.validators.MaxValueValidator(999, message='La cantidad máxima es 999.')])),
                ('precio_unitario', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000000, message='El precio no puede superar $10.000.000.')], verbose_name='Precio unitario neto (CLP)')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mascotas.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de factura',
                'verbose_name_plural': 'Detalles de factura',
                'ordering': ['id'],
            },
        ),
    ]
