# Generated by Django 4.2.30 on 2026-09-30 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0008_factura_detallefactura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('categoria', models.CharField(choices=[('medicamento', 'Medicamento'), ('vacuna', 'Vacuna'), ('alimento', 'Alimento'), ('insumo', 'Insumo clínico'), ('otro', 'Otro')], default='medicamento', max_length=20, verbose_name='Categoría')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock actual')),
                ('stock_minimo', models.PositiveIntegerField(default=5, help_text='Bajo esta cantidad el producto pasa a amarillo.', validators=[django.core.validators.MinValueValidator(1, message='El stock mínimo debe ser al menos 1.')], verbose_name='Stock mínimo')),
                ('unidad', models.CharField(default='unidad', help_text='Ej: unidad, caja, frasco, kg.', max_length=30)),
                ('precio_venta', models.PositiveIntegerField(default=0, verbose_name='Precio de venta neto (CLP)')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar si ya no se trabaja con este producto.')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
