# Generated by Django 4.2.30 on 2026-09-30 21:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0009_producto_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='alerta_enviada_el',
            field=models.DateTimeField(blank=True, help_text='Momento en que se envió el recordatorio de esta cita por correo.', null=True, verbose_name='Recordatorio enviado el'),
        ),
        migrations.AddField(
            model_name='cita',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, help_text='Cuánto seاليات la consulta. Opcional.', null=True, validators=[django.core.validators.MinValueValidator(5, message='La duración mínima es 5 minutos.'), django.core.validators.MaxValueValidator(480, message='La duración máxima es 480 minutos (8 horas).')], verbose_name='Duración (minutos)'),
        ),
        migrations.AddField(
            model_name='dueño',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad donde vive el dueño (opcional).', max_length=80, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('en_tratamiento', 'En tratamiento'), ('recuperando', 'Recuperando'), ('fallecido', 'Fallecido')], default='activo', help_text='Estado general de la mascota en la clínica.', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Se usa para calcular la edad al mostrar la ficha. Opcional.', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, help_text='Fotografía de la mascota (opcional).', null=True, upload_to='mascotas/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso actual en kilogramos (opcional).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='El peso debe ser mayor a 0.')], verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], default='', max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='dueño',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo para notificaciones. No puede repetirse entre dueños.', max_length=150, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(help_text='Nombre del medicamento recetado (ej: Amoxicilina 500mg).', max_length=120, verbose_name='Medicamento')),
                ('dosis', models.CharField(help_text='Cómo se administra (ej: 1 comprimido cada 12 horas).', max_length=120, verbose_name='Dosis')),
                ('duracion_dias', models.PositiveIntegerField(help_text='Cuántos días debe seguir el tratamiento.', validators=[django.core.validators.MinValueValidator(1, message='La duración mínima es 1 día.'), django.core.validators.MaxValueValidator(365, message='La duración máxima es 365 días.')], verbose_name='Duración (días)')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de la indicación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('receta_lista_el', models.DateTimeField(blank=True, help_text='Momento en que se avisó al dueño que la receta está lista.', null=True, verbose_name='Aviso de receta enviada el')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='mascotas.cita', verbose_name='Cita')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-fecha'],
                'permissions': [('view_own_recetas', 'Puede ver solo sus propias recetas')],
            },
        ),
    ]
